services:
  backend:
    build: ./server
    ports:
      - "3010:3007"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=SANdatabase7$$
      - DB_NAME=lara_store
    depends_on:
      - mysql
    command:
      ["/wait-for-it.sh", "mysql:3306", "--", "node", "server.js"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql:
    image: mysql:8
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SANdatabase7$$
      MYSQL_DATABASE: lara_store
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
